version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/src/renderer"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "auto-merge"
  
  - package-ecosystem: "cargo"
    directory: "/src-tauri"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "auto-merge"
  
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "ci"
      - "auto-merge"
